disabled_rules:
  - colon
  - comma
  - opening_brace
  - trailing_whitespace
  - no_space_in_method_call
  - closure_parameter_position
  - operator_whitespace
  - identifier_name
  - statement_position
  - unused_setter_value

opt_in_rules:

included:
  - Coordinator
  - Parsec
  - Neuronific
  - ParsecTests

excluded:

opt_in_rules:
  - file_header

file_header:
  excluded: 
    - Parsec
    - ParsecTests
  included:
    - Parsec/Components
  severity: error
  required_pattern: |
                    \/\/
                    \/\/  This file is distributed under the same license as the NEURONIFIC \(PTY\) LTD package\.
                    \/\/  Copyright \(c\) \d{4} and Confidential to NEURONIFIC \(PTY\) LTD\. All rights reserved\.
                    \/\/
